from pathlib import Path

import structlog
from config.core_models import SimulationParams, TargetColor
from config.module_params import PlannerModuleConfig, TrajGeneratorType
from pydantic import BaseModel
from utils_common.custom_types import NdArray


class PlannerData(BaseModel):
    "Holds data generated by the planner for plotting purposes"

    trajectory: NdArray
    choice: TargetColor

    class Config:
        arbitrary_types_allowed = True


def generate_traj(
    params: PlannerModuleConfig,
    sim: SimulationParams,
    input_image_path: Path,
    traj_out_path: Path,
):
    log = structlog.get_logger("main.generate_signals")

    traj_gen_type = params.trajgen_type
    traj = choice = None
    log.info(f"Generating trajectory using '{traj_gen_type}' planner...")

    if traj_gen_type == TrajGeneratorType.MOCKED:
        from complete_control.utils_common.generate_signals_minjerk import (
            generate_trajectory_minjerk,
        )

        traj = generate_trajectory_minjerk(sim)
        choice = sim.oracle.target_color.value
    elif traj_gen_type == TrajGeneratorType.GLE:
        from complete_control.utils_common.generate_signals_gle import (
            generate_trajectory_gle,
        )

        traj, idx_choice = generate_trajectory_gle(
            input_image_path, sim, params.gle_config
        )
        choice = TargetColor.BLUE_LEFT if idx_choice == 0 else TargetColor.RED_RIGHT
    else:
        raise NotImplementedError(f"Unknown planner type: {traj_gen_type}")

    data = PlannerData(trajectory=traj, choice=choice)
    with open(traj_out_path, "w") as f:
        f.write(data.model_dump_json(indent=2))

    return traj


def generate_mock_motor_commands(
    sim: SimulationParams,
):
    from complete_control.utils_common.generate_signals_minjerk import (
        generate_motor_commands_minjerk,
    )

    log = structlog.get_logger("main.generate_signals")
    log.info(f"Generating motor commands...")

    return generate_motor_commands_minjerk(sim)
